# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsernameValidationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='username',
            new_name='usernameDB',
        ),
    ]
