# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('likes', models.IntegerField(default=0)),
                ('fk_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_creator', to='LogReg.userDB')),
            ],
        ),
    ]
