# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheWall', '0002_auto_20170520_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_id',
            new_name='message',
        ),
    ]
