# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_auto_20170516_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='book_id',
        ),
    ]
