# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='first_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='userdb',
            old_name='last_name',
            new_name='name',
        ),
    ]
