# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secrets', '0002_remove_userdb_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretdb',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
