# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secrets', '0004_auto_20170529_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='likeDB',
        ),
    ]
